<a href="https://colab.research.google.com/github/Saurabh312Kumar/ML-Concepts/blob/main/MultinomialNaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import string
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report)

In [29]:
df = pd.read_csv("spam.csv", encoding="latin-1")

df.head()

     v1  ... Unnamed: 4
0   ham  ...        NaN
1   ham  ...        NaN
2  spam  ...        NaN
3   ham  ...        NaN
4   ham  ...        NaN

[5 rows x 5 columns]

In [30]:
df.shape

(5572, 5)

In [31]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [32]:
df=df[['v1','v2']]
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [33]:
df.columns = ['target', 'text']
df.head()

  target                                               text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [34]:
df['target'].value_counts()

target
ham     4825
spam     747
Name: count, dtype: int64

In [35]:
lb=LabelEncoder()
df['target']=lb.fit_transform(df['target'])
df.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [36]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [37]:
ps = PorterStemmer()

In [38]:
def clean_text(text):
  text=text.lower()

  word_tokens=word_tokenize(text=text)

  word_tokens=[word for word in word_tokens if word.isalnum()]

  word_tokens=[word for word in word_tokens if word not in stopwords.words('english')]

  word_tokens=[ps.stem(word) for word in word_tokens]

  return " ".join(word_tokens)

In [39]:
df['clean_text'] = df['text'].apply(clean_text)

df[['text', 'clean_text']].head()

                                                text                                         clean_text
0  Go until jurong point, crazy.. Available only ...  go jurong point crazi avail bugi n great world...
1                      Ok lar... Joking wif u oni...                              ok lar joke wif u oni
2  Free entry in 2 a wkly comp to win FA Cup fina...  free entri 2 wkli comp win fa cup final tkt 21...
3  U dun say so early hor... U c already then say...                u dun say earli hor u c alreadi say
4  Nah I don't think he goes to usf, he lives aro...               nah think goe usf live around though

In [40]:
X=df['clean_text']
y=df['target']

In [41]:
X_train,X_test,y_train,y_test=train_test_split(X,y,stratify=y,test_size=0.2,random_state=42)

In [42]:
tfidf = TfidfVectorizer()

X_train_tfidf = tfidf.fit_transform(X_train)

X_test_tfidf = tfidf.transform(X_test)

In [45]:
mnb=MultinomialNB()
mnb.fit(X_train_tfidf,y_train)

MultinomialNB()

In [46]:
y_pred = mnb.predict(X_test_tfidf)

In [48]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy : 0.9614349775784753
Precision: 0.9907407407407407
Recall   : 0.7181208053691275
F1 Score : 0.8326848249027238

Confusion Matrix:
[[965   1]
 [ 42 107]]

Classification Report:
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       966
           1       0.99      0.72      0.83       149

    accuracy                           0.96      1115
   macro avg       0.97      0.86      0.91      1115
weighted avg       0.96      0.96      0.96      1115

In [51]:
message = ["Congratulations! You won a free iPhone. Click now to claim."]

message_clean=[clean_text(message[0])]
message_tfidf=tfidf.transform(message_clean)

prediction = mnb.predict(message_tfidf)

if prediction[0] == 1:
    print("Spam")
else:
    print("Not Spam")

Spam

In [53]:
message = ["WINNER!! You have won a FREE prize! Call now."]

message_clean=[clean_text(message[0])]
message_tfidf=tfidf.transform(message_clean)

prediction = mnb.predict(message_tfidf)

if prediction[0] == 1:
    print("Spam")
else:
    print("Not Spam")

Spam